name: Test defaults.yml

on:
  push:
    paths:
      - 'defaults.yml'
      - 'defaults-*.yml'

  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@master

    - name: Lint defaults.yml
      uses: ibiqlik/action-yamllint@v3.1.1
      with:
        file_or_dir: defaults.yml
        config_file: .github/workflows/config/yml-lint.yml
        strict: true

    - name: Lint defaults-fr.yml
      uses: ibiqlik/action-yamllint@v3.1.1
      with:
        file_or_dir: defaults-fr.yml
        config_file: .github/workflows/config/yml-lint.yml
        strict: true

    - name: Validate 'defaults-*.yml' against schema
      uses: nwisbeta/validate-yaml-schema@v2.0.0
